### ISSUE TITLE
Remover página series

### ISSUE THREAD

**Issue by ferfabricio** [DeveloperParana/blog#10]
Remover do blog item series

**Comment by renanmpimentel** [comment]
Acho que dá para manter esse item, por exemplo, se for escrever vários artigos sequenciais de alguma tecnologia, fica mais facil encontrar ali ..

Por exemplo:
- Iniciando com o GIT #**1**
- Como usar o GitHub #**2** 

E por ai vai.. para separar isso, basta usar a opção `categories:` ( https://github.com/DeveloperParana/blog/blob/gh-pages/initpost.sh#L119 ) quando fizer parte de uma serie de posts.

**Comment by renanmpimentel** [comment]
Como ninguem se manifestou, vou fechar essa issue.
